name: Build home

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
    paths:
      - 'packages/home/**'
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Install deps
        run: pnpm -F opentiny-design-home i --no-frozen-lockfile
      - name: Build home
        run: pnpm build
